version: "3.7"
services:
  proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    container_name: proxy
    ports:
      - "8080:8080"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend
  server1:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server1
    expose:
      - "3000"
    restart: "unless-stopped"
    networks:
      - backend

volumes:
  data:
    driver: local

networks:
  backend:
    driver: bridge
